name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Wow ${{ github.base_ref }} - ${{ github.head_ref }}"
      - run: |
          sudo apt-get update && sudo apt-get -y install jq git
          git clone https://github.com/${{ github.repository }} -b `echo ${{ github.ref }} | cut -d'/' -f3`
          cd tools.tldr.run/tools
          if [ $(cat *.json | jq '.name' | uniq | wc -l) -ne $(cat *.json | jq '.name' | wc -l) ]; echo "Duplicate entry"; then exit 1; fi
#     - run: |
#         git clone https://github.com/${{ github.repository }}
#         cd tools.tldr.run
#         git checkout `echo ${{ github.ref }} | cut -d'/' -f3` && git fetch
#         git diff --name-status main..`echo ${{ github.ref }} | cut -d'/' -f3`         
#      - name: Check out repository code
#        uses: actions/checkout@v2
#      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
